export const background = {
  fire: '#FFA756',
  normal: '#B5B9C4',
  fighting: '#EB4971',
  flying: '#748FC9',
  poison: '#9F6E97',
  ground: '#F78551',
  rock: '#BAAB82',
  bug: '#8BD674',
  ghost: '#8571BE',
  steel: '#4C91B3',
  water: '#58ABF6',
  grass: '#8BBE8A',
  electric: '#F2CB55',
  fairy: '#EBA8C3',
  ice: '#91D8DF',
  psychic: '#FF6568',
}

export const color = {
  fire: '#FD7D24',
  normal: '#9DA0AA',
  fighting: '#D04164',
  flying: '#748FC9',
  poison: '#A552CC',
  ground: '#DD7748',
  rock: '#BAAB82',
  bug: '#8CB330',
  ghost: '#556AAE',
  steel: '#417D9A',
  water: '#4A90DA',
  grass: '#62B957',
  electric: '#EED535',
  fairy: '#ED6EC7',
  ice: '#61CEC0',
  psychic: '#EA5D60'
}

export const images = {
  fire: `${require('../assets/types/fire.png')}`,
  normal: `${require('../assets/types/normal.png')}`,
  fighting: `${require('../assets/types/fighting.png')}`,
  flying: `${require('../assets/types/flying.png')}`,
  poison: `${require('../assets/types/poison.png')}`,
  ground: `${require('../assets/types/ground.png')}`,
  rock: `${require('../assets/types/rock.png')}`,
  bug: `${require('../assets/types/bug.png')}`,
  ghost: `${require('../assets/types/ghost.png')}`,
  steel: `${require('../assets/types/steel.png')}`,
  water: `${require('../assets/types/water.png')}`,
  grass: `${require('../assets/types/grass.png')}`,
  electric: `${require('../assets/types/electric.png')}`,
  fairy: `${require('../assets/types/fairy.png')}`,
  ice: `${require('../assets/types/ice.png')}`,
  psychic: `${require('../assets/types/psychic.png')}`,
}