export default [
  {
    id: 1,
    name: 'normal',
    color: '#9DA0AA',
    background: '#B5B9C4',
    image: `${require('../assets/types/normal.png')}`,
  },
  {
    id: 2,
    name: 'fighting',
    color: '#D04164',
    background: '#EB4971',
    image: `${require('../assets/types/fighting.png')}`,
  },
  {
    id: 3,
    name: 'flying',
    color: '#748FC9',
    background: '#EB4971',
    image: `${require('../assets/types/fighting.png')}`,
  },
  {
    id: 4,
    name: 'poison',
    color: '#A552CC',
    background: '#9F6E97',
    image: `${require('../assets/types/fighting.png')}`,
  },
  {
    id: 5,
    name: 'ground',
    color: '#DD7748',
    background: '#F78551',
    image: `${require('../assets/types/ground.png')}`,
  },
  {
    id: 6,
    name: 'rock',
    color: '#BAAB82',
    background: '#BAAB82',
    image: `${require('../assets/types/rock.png')}`,
  },
  {
    id: 7,
    name: 'bug',
    color: '#8CB330',
    background: '#8BD674',
    image: `${require('../assets/types/bug.png')}`,
  },
  {
    id: 8,
    name: 'ghost',
    color: '#556AAE',
    background: '#556AAE',
    image: `${require('../assets/types/ghost.png')}`,
  },
  {
    id: 9,
    name: 'steel',
    color: '#417D9A',
    background: '#417D9A',
    image: `${require('../assets/types/steel.png')}`,
  },
]